# Generated by Django 4.0.6 on 2022-07-14 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
